export const TEACHER_LOG_ACTIONS = {
  ATTENDANCE_SUBMIT: 'ATTENDANCE_SUBMIT',
  ATTENDANCE_MISSING: 'ATTENDANCE_MISSING',
  PAPER_UPLOAD: 'PAPER_UPLOAD',
  PAPER_PUBLISH: 'PAPER_PUBLISH',
  PERFORMANCE_POST: 'PERFORMANCE_POST',
  CLASSROOM_FEEDBACK_DRAFT: 'CLASSROOM_FEEDBACK_DRAFT',
  CLASSROOM_FEEDBACK_PUBLISH: 'CLASSROOM_FEEDBACK_PUBLISH',
  LEARNING_GOAL_SAVE: 'LEARNING_GOAL_SAVE',
  WEAKNESS_SAVE: 'WEAKNESS_SAVE',
  STAGE_SUMMARY_DRAFT: 'STAGE_SUMMARY_DRAFT',
  STAGE_SUMMARY_PUBLISH: 'STAGE_SUMMARY_PUBLISH',
  COMMENT_REPLY: 'COMMENT_REPLY',
  TEACHER_LOGIN: 'TEACHER_LOGIN',
  MAKEUP_ARRANGE: 'MAKEUP_ARRANGE',
} as const

export type TeacherLogAction = keyof typeof TEACHER_LOG_ACTIONS
