import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

/**
 * 新乐市学生可报学校说明（2025年）：
 *
 * ✅ 可以报考：
 *   1. 新乐本地学校：新乐一中（含分配生）、新乐二中、三中、四中、新伏羲中学
 *   2. 驻县四所市级计划：辛集中学(市)=725分、正定中学(市)=724分、
 *      实验中学(市)=740分、第二实验中学(市)=727分
 *   3. 四十二中(县)计划：统招751分，控制线718分（与驻县四所同标准）
 *   4. 所有民办学校"其他县区"计划（见学校名称含"其他县区"字样）
 *
 * ❌ 不可报考：
 *   - 其他县区的县级公办高中（如藁城、正定、行唐等县公办）
 *   - 市区公办高中（一中、二中等，需市区户籍）
 *
 * 数据来源：2025年石家庄市中考官方录取分数线（石家庄市教育考试院，2025.7.20公布）
 * 总分说明：2025年石家庄中考总分800分
 */
const schools = [
  {
    schoolId: 'xl1', name: '新乐一中', fullName: '新乐市第一中学', type: '省示范', location: '新乐',
    address: '河北省新乐市区西北部', distanceFromXinle: '市区内，骑车可达',
    yiTong: 725, tongZhao: 678, enrollment: 900, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '新乐本地最好高中，省级示范校，高考本科率超90%',
    gaokaoRate: '本科上线率约90%+，2017年本科上线1075人',
    intro: '建于1956年，省级示范性高中。占地93573平方米，现有高中教学班60个，在校生3400余人。连续8年被评为石家庄市高中教学工作先进单位，高考成绩连年攀升。拥有标准体育运动场、图书馆、多功能报告厅等完善设施。',
    tips: '新乐本地学生首选。分配生名额全市最多（1130个），本地学生优势极大。走分配生通道录取确定性远高于统招，强烈建议符合条件的学生优先考虑分配生通道。',
    website: 'http://www.xlyz1.cn', phone: '0311-88789001',
  },
  {
    schoolId: 'xl2', name: '新乐二中', fullName: '新乐市第二中学', type: '县中', location: '新乐',
    address: '河北省新乐市区', distanceFromXinle: '市区内',
    yiTong: null, tongZhao: 624, enrollment: 400, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '新乐本地公办县中，入学门槛适中',
    gaokaoRate: '本科上线率约60-70%',
    intro: '新乐市公办普通高中，是新乐一中之外的本地第二选择。学校管理规范，适合成绩中等、希望在本地就读的学生。',
    tips: '适合中等成绩学生的稳妥选择，无需跨市就读，家庭花费相对较低。',
    phone: '0311-88789002',
  },
  {
    schoolId: 'xl3', name: '新乐三中', fullName: '新乐市第三中学', type: '县中', location: '新乐',
    address: '河北省新乐市', distanceFromXinle: '市区内',
    yiTong: null, tongZhao: 489, enrollment: 300, boardingAvail: false,
    tuitionFee: '公办，学费全免', keyFeature: '新乐本地公办高中，录取门槛较低',
    gaokaoRate: '本科上线率约40-50%',
    intro: '新乐市公办普通高中，统招线489分，是新乐本地录取门槛较低的公办选择。',
    tips: '适合分数未达到一中、二中要求的本地学生就近就读。',
  },
  {
    schoolId: 'xl4', name: '新乐四中', fullName: '新乐市第四中学', type: '县中', location: '新乐',
    address: '河北省新乐市', distanceFromXinle: '市区内',
    yiTong: null, tongZhao: 583, enrollment: 300, boardingAvail: false,
    tuitionFee: '公办，学费全免', keyFeature: '新乐本地公办高中',
    gaokaoRate: '本科上线率约50-60%',
    intro: '新乐市公办普通高中，统招线583分。',
    tips: '本地就读，无需住宿，家庭负担小。',
  },
  {
    schoolId: 'xl5', name: '新伏羲中学（新乐）', fullName: '新乐市新伏羲中学', type: '民办', location: '新乐',
    address: '河北省新乐市', distanceFromXinle: '市区内',
    yiTong: null, tongZhao: 660, enrollment: 200, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费约1-2万/学年（以学校公布为准）',
    keyFeature: '新乐本地民办高中，管理严格',
    intro: '新乐市民办高中，管理相对严格，住宿条件较好。',
    tips: '民办学校学费较高，报考前请详细了解学费标准及奖学金政策。',
  },
  {
    schoolId: 'szjz1', name: '河北正定中学（正定）', fullName: '河北正定中学', type: '省示范', location: '正定',
    address: '石家庄市正定县府西街80号', distanceFromXinle: '距新乐约40公里，车程约1小时',
    yiTong: 770, tongZhao: 769, enrollment: 1200, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '全省顶尖高中，2022年清北上线11人，985上线率超30%',
    gaokaoRate: '本一率100%，985率30%+，211率60%+',
    intro: '河北省最顶尖高中之一，百年名校。下设本部和东校区（正中实验，民办）。本部公办免费，入学要求极高。设竞赛班、领航班等精英班型，师资力量全省顶配。2022年清北上线11人，985上线387人。',
    tips: '新乐学生报考正定校区（非市区校区），统招线769分，竞争极激烈。对于新乐学生来说属于顶级冲刺目标，分数须在720分以上才有把握。需要住校，生活费另计。其他县区（含新乐）统招线为 724 分（正定中学-市计划），正定本地为 760 分。',
    website: 'http://www.zhengzhong.cn', phone: '0311-88042114',
  },
  {
    schoolId: 'szjz2', name: '辛集中学', fullName: '河北辛集中学', type: '省示范', location: '辛集',
    address: '河北省辛集市', distanceFromXinle: '距新乐约70公里，车程约1.5小时',
    yiTong: 749, tongZhao: 743, enrollment: 800, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '驻县四所省示范高中之一，高考成绩优异',
    gaokaoRate: '本一率95%+',
    intro: '河北省驻县四所顶级公办省示范高中之一（与正定中学、石家庄实验中学、石家庄第二实验中学并列）。高考成绩优秀，本一率稳定在95%以上。',
    tips: '新乐学生（其他县区）统招线743分，属于高难度冲刺目标。需要住校，路途较远，家长要考虑接送问题。有分配生名额，符合条件的学生可优先走分配生通道。其他县区（含新乐）统招线为 725 分（辛集中学-市计划）。',
  },
  {
    schoolId: 'szjz3', name: '石家庄实验中学', fullName: '石家庄实验中学', type: '省示范', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里，车程约1小时',
    yiTong: 761, tongZhao: 759, enrollment: 1000, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '驻县四所之一，石家庄市顶尖公办高中',
    gaokaoRate: '本一率近100%',
    intro: '石家庄市顶尖公办省示范高中，驻县四所之一。高考成绩顶尖，一统线761分，统招线759分，竞争极为激烈。',
    tips: '新乐学生入学门槛极高（统招线759分），属于顶尖学生目标。在石家庄市区就读，距新乐较远，需全程住校。',
  },
  {
    schoolId: 'szjz4', name: '石家庄第二实验中学', fullName: '石家庄第二实验中学', type: '省示范', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 752, tongZhao: 727, enrollment: 1000, boardingAvail: true,
    boardingFee: '约300元/学期', tuitionFee: '公办，学费全免',
    keyFeature: '驻县四所之一，高考实力强劲', gaokaoRate: '本一率98%+',
    intro: '石家庄市驻县四所顶级公办省示范高中之一，高考成绩优异。',
    tips: '新乐学生（其他县区）统招线727分，难度较高。需住校，在市区就读。',
  },
  {
    schoolId: 'mb1', name: '二中实验学校（其他县区）', fullName: '石家庄二中实验学校', type: '民办', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 763, tongZhao: 750, enrollment: 1800, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，约3.9-5万元/学年（按班型不同）',
    keyFeature: '石家庄最强民办高中，高考成绩顶尖',
    gaokaoRate: '重本率超高，竞赛班冲刺清北',
    intro: '依托石家庄二中（公办）资源创办的民办高中，是石家庄最顶尖的民办高中。设竞赛班、领航班、平行班，学费按班型差异较大（3.9-5万/学年）。2022年600分以上236人，重本836人，本一线上线1431人。',
    tips: '学费较高，但教学质量顶尖。新乐学生（其他县区）统招线750分，有分配生名额。适合追求顶尖高考成绩且家庭经济条件较好的学生。',
  },
  {
    schoolId: 'mb2', name: '正中实验中学（其他县区）', fullName: '河北正中实验中学', type: '民办', location: '市区',
    address: '石家庄市（正定中学东校区）', distanceFromXinle: '距新乐约40公里',
    yiTong: 755, tongZhao: 746, enrollment: 1800, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，约3.9-5万元/学年',
    keyFeature: '正定中学旗下民办，侧重高考成绩提升，211录取率超60%',
    gaokaoRate: '211录取率60%+，本一率高',
    intro: '隶属正定中学的民办校区，定位普惠优质，2025年招生计划1800人，211录取率超60%。',
    tips: '性价比较高的民办选择，有新乐分配生名额。学费约3.9-5万/学年，比二中实验略低，但教学质量同样出色。',
  },
  {
    schoolId: 'mb3', name: '润德学校（其他县区）', fullName: '润德学校', type: '民办', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 759, tongZhao: 752, enrollment: 600, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，约2-4万元/学年（以学校公布为准）',
    keyFeature: '石家庄知名民办高中，高考成绩较好',
    intro: '石家庄市知名民办高中，一统线759分，统招线752分，录取门槛较高。',
    tips: '新乐有分配生名额，高分段学生可考虑。学费较高，报考前请咨询学校最新收费标准。',
  },
  {
    schoolId: 'mb4', name: '精英中学（其他县区）', fullName: '精英中学', type: '民办', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 775, tongZhao: 743, enrollment: 800, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，约5000-2.145万元/学期（按班型）',
    keyFeature: '一统线全市最高（775分），顶尖学生聚集地',
    gaokaoRate: '重本率极高',
    intro: '2025年一统线全市民办最高（775分），是石家庄顶尖民办高中。吸引全市最顶尖生源，高考成绩出色。学费按班型从5000元到21450元/学期不等。',
    tips: '2025年其他县区（含新乐市）一统线 775 分，统招线 743 分。一统线775分，门槛极高，面向新乐最顶尖学生。有分配生名额，但分数要求极高。学费相对较高。',
  },
  {
    schoolId: 'mb5', name: '一中实验学校（其他县区）', fullName: '石家庄一中实验学校', type: '民办', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 744, tongZhao: 741, enrollment: 600, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费较高（以学校公布为准）',
    keyFeature: '依托石家庄一中资源，高考成绩出色',
    intro: '隶属石家庄一中的民办校区，高考成绩优异，一统线744分，统招线741分。',
    tips: '有新乐分配生名额，门槛较高（741分+）。民办学费较高，建议提前了解。',
  },
  {
    schoolId: 'mb6', name: '联邦外国语学校（其他县区）', fullName: '河北联邦外国语学校', type: '民办', location: '市区',
    address: '石家庄市', distanceFromXinle: '距新乐约60公里',
    yiTong: 713, tongZhao: 540, enrollment: 400, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费较高',
    keyFeature: '外语特色学校，统招线540分，录取门槛低',
    intro: '以外语教学为特色的民办高中，统招线540分，相对门槛较低，适合英语较强的学生。',
    tips: '统招线仅540分，是门槛较低的市区民办选择。有新乐分配生名额，分配线为一统线-50=663分。以外语为特色，适合英语能力强的学生。',
  },
  {
    schoolId: 'mb7', name: '敬业中学（其他县区）', fullName: '敬业中学', type: '民办', location: '平山',
    address: '石家庄市平山县', distanceFromXinle: '距新乐约80公里，车程约1.5小时',
    yiTong: 732, tongZhao: 698, enrollment: 500, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费较高',
    keyFeature: '平山知名民办高中',
    intro: '位于平山县的民办高中，一统线732分，统招线698分。',
    tips: '距新乐较远，需全程住校。有新乐分配生名额。',
  },
  {
    schoolId: 'mb8', name: '金石高级中学（其他县区）', fullName: '金石高级中学有限公司', type: '民办', location: '鹿泉',
    address: '石家庄市鹿泉区', distanceFromXinle: '距新乐约70公里',
    yiTong: 666, tongZhao: 608, enrollment: 400, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费中等',
    keyFeature: '鹿泉民办高中，门槛适中',
    intro: '位于鹿泉区的民办高中，一统线666分，统招线608分，录取门槛适中。',
    tips: '有新乐分配生名额，门槛相对较低（608分），适合中等偏上成绩学生。',
  },
  {
    schoolId: 'mb9', name: '卓越中学东校区（其他县区）', fullName: '卓越中学东校区', type: '民办', location: '鹿泉',
    address: '石家庄市鹿泉区', distanceFromXinle: '距新乐约70公里',
    yiTong: 663, tongZhao: 624, enrollment: 400, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费中等',
    keyFeature: '鹿泉卓越中学东校区',
    intro: '位于鹿泉区，卓越中学东西两个校区之一，一统线663分，统招线624分。',
    tips: '有新乐分配生名额，门槛适中。',
  },
  {
    schoolId: 'mb10', name: '卓越中学西校区（其他县区）', fullName: '卓越中学西校区', type: '民办', location: '鹿泉',
    address: '石家庄市鹿泉区', distanceFromXinle: '距新乐约70公里',
    yiTong: 717, tongZhao: 672, enrollment: 400, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费中等',
    keyFeature: '鹿泉卓越中学西校区，比东校区门槛更高',
    intro: '卓越中学西校区，一统线717分，统招线672分，高于东校区。',
    tips: '有新乐分配生名额。',
  },
  {
    schoolId: 'mb11', name: '精英新华中学（其他县区）', fullName: '精英新华中学', type: '民办', location: '鹿泉',
    address: '石家庄市鹿泉区', distanceFromXinle: '距新乐约70公里',
    yiTong: 735, tongZhao: 695, enrollment: 400, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费较高',
    keyFeature: '精英旗下新华校区，高考成绩较好',
    intro: '精英教育集团旗下学校，一统线735分，统招线695分。',
    tips: '有新乐分配生名额，门槛较高（695分）。',
  },
  {
    schoolId: 'mb12', name: '行唐启明中学（其他县区）', fullName: '行唐启明中学', type: '民办', location: '行唐',
    address: '石家庄市行唐县', distanceFromXinle: '距新乐约40公里',
    yiTong: 699, tongZhao: 674, enrollment: 300, boardingAvail: true,
    boardingFee: '住宿费另计', tuitionFee: '民办，学费中等',
    keyFeature: '行唐知名民办高中，距新乐较近',
    intro: '位于行唐县，是距新乐较近的外县民办高中选择，一统线699分，统招线674分。',
    tips: '距新乐相对较近（约40公里），有新乐分配生名额，适合不想去太远学校的学生。',
  },

  // ===== 第一批补充：市区顶尖公办（新乐学生注意跨区限制）=====
  {
    schoolId: 'sz01',
    name: '石家庄一中',
    fullName: '石家庄市第一中学',
    type: '省示范',
    location: '市区（长安区）',
    address: '石家庄市长安区',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 776,
    tongZhao: 765,
    enrollment: 1000,
    boardingAvail: true,
    boardingFee: '公办免费住宿',
    tuitionFee: '公办，学费全免',
    keyFeature: '石家庄最顶尖公办高中之一，本一率99%+，清北每年数十人',
    gaokaoRate: '本一率99%+，每年清北录取人数全市前列',
    intro: '石家庄市最顶尖公办高中，省级示范性高中。2025年招生约1000人（含特长生、自主招生119人）。设有理科实验班、重点班等。高考成绩顶尖，本一率长年保持99%以上，每年清北录取人数位居全市前列。',
    tips: '⚠️ 新乐学生通常无法报考！2025年起市区公办高中实行跨区限制，报考需要目标学区（长安区）户籍或房产。新乐只有藁城、鹿泉、栾城三区考生可报部分市区校，新乐市不在范围内。本栏信息仅供了解石家庄高中整体水平参考。',
    phone: '0311-86666001',
  },
  {
    schoolId: 'sz02',
    name: '石家庄二中',
    fullName: '石家庄市第二中学',
    type: '省示范',
    location: '市区（裕华区）',
    address: '石家庄市裕华区',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 785,
    tongZhao: 765,
    enrollment: 1115,
    boardingAvail: true,
    boardingFee: '公办住宿费约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '全省最顶尖高中，一统线785分全市最高，本一率100%',
    gaokaoRate: '本一率100%，年清北40余人，理科650分以上45.5%',
    intro: '河北省最顶尖高中，一统线785分为全市最高。2025年招生约1115人（含航空特色班100人）。高考成绩全省顶尖，理科本一率100%，每年清北录取人数40余人。设省理科实验班、重点班等顶尖班型。',
    tips: '⚠️ 新乐学生通常无法报考！报考需裕华区户籍或房产。一统线785分为全市最高，是河北省最顶尖高中。本栏信息供了解参考，新乐学生实际无法报考此校。',
    phone: '0311-85815012',
  },
  {
    schoolId: 'sz03',
    name: '一中滨河校区',
    fullName: '石家庄市第一中学滨河校区',
    type: '省示范',
    location: '市区（正定新区）',
    address: '石家庄市正定新区',
    distanceFromXinle: '距新乐约50公里',
    yiTong: 756,
    tongZhao: 749,
    enrollment: 1380,
    boardingAvail: true,
    boardingFee: '公办住宿费约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '一中在正定新区的校区，招生规模大，有正定新区专项计划',
    gaokaoRate: '本一率95%+',
    intro: '石家庄一中滨河校区位于正定新区，2025年招生计划1380人，是招生规模最大的市区公办校区之一。另有正定新区专项计划230人。',
    tips: '⚠️ 新乐学生通常无法报考！以藁城、鹿泉、栾城三区和正定新区学生为主，新乐市不在报考范围内。',
  },
  {
    schoolId: 'sz04',
    name: '二中铭德校区',
    fullName: '石家庄市第二中学铭德校区',
    type: '省示范',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 761,
    tongZhao: 752,
    enrollment: 800,
    boardingAvail: true,
    boardingFee: '公办住宿费约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '石家庄二中铭德校区，高考成绩顶尖',
    gaokaoRate: '本一率98%+',
    intro: '石家庄二中铭德校区，2025年招生800人，一统线761分，统招线752分。',
    tips: '⚠️ 新乐学生通常无法报考，需市区户籍。',
  },
  {
    schoolId: 'sz05',
    name: '石家庄四十二中（外国语）',
    fullName: '石家庄市第四十二中学',
    type: '省示范',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 770,
    tongZhao: 747,
    enrollment: 800,
    boardingAvail: true,
    boardingFee: '公办住宿约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '石家庄著名外语特色高中，有县区招生计划',
    gaokaoRate: '本一率97%+',
    intro: '石家庄著名外语特色高中，一统线770分。四十二中（县）有面向各县区的招生计划（统招线751分），是少数对外县区开放招生的顶尖市区公办校。',
    tips: '四十二中有"县"字校区面向各县区招生（统招线751分），但具体是否接受新乐市学生报考，需向学校招生办核实。一统线770分，难度极高。',
    phone: '0311-86029870',
  },
  {
    schoolId: 'sz06',
    name: '石家庄四十三中（外国语）',
    fullName: '石家庄市第四十三中学',
    type: '省示范',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 774,
    tongZhao: 746,
    enrollment: 700,
    boardingAvail: true,
    boardingFee: '公办住宿约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '石家庄外国语学校，外语特色突出，升学率高',
    gaokaoRate: '本一率97%+',
    intro: '以外语教育为特色的省级示范高中，一统线774分，统招线746分。是石家庄重点外语类高中。',
    tips: '⚠️ 新乐学生通常无法报考，需市区户籍，仅供参考。',
  },
  {
    schoolId: 'sz07',
    name: '师大附中',
    fullName: '河北师范大学附属中学',
    type: '省示范',
    location: '市区',
    address: '石家庄市裕华区南二环东路20号',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 733,
    tongZhao: 724,
    enrollment: 700,
    boardingAvail: true,
    boardingFee: '公办住宿约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '依托河北师范大学，人文特色突出，高考成绩优秀',
    gaokaoRate: '本一率97%+，清北每年数人',
    intro: '依托河北师范大学创办的附属中学，省级示范性高中。人文特色突出，师资力量雄厚。一统线733分，统招线724分，高考成绩优秀。',
    tips: '⚠️ 新乐学生通常无法报考，需市区户籍。本栏供了解石家庄高中格局参考。',
  },
  {
    schoolId: 'sz08',
    name: '石家庄二十四中',
    fullName: '石家庄市第二十四中学',
    type: '省示范',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 757,
    tongZhao: 742,
    enrollment: 700,
    boardingAvail: true,
    boardingFee: '公办住宿约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '市区重点省示范高中',
    gaokaoRate: '本一率95%+',
    intro: '石家庄市区省级示范高中，一统线757分，统招线742分。',
    tips: '⚠️ 新乐学生通常无法报考，需市区户籍。',
  },
  {
    schoolId: 'sz09',
    name: '石家庄十七中',
    fullName: '石家庄市第十七中学',
    type: '省示范',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 741,
    tongZhao: 738,
    enrollment: 600,
    boardingAvail: false,
    tuitionFee: '公办，学费全免',
    keyFeature: '人文特色突出，石家庄知名公办省示范',
    gaokaoRate: '本一率95%+',
    intro: '石家庄市区省级示范高中，以人文教育为特色，一统线741分，统招线738分。',
    tips: '⚠️ 新乐学生通常无法报考，需市区户籍。',
  },

  // ===== 第二批补充：其他县区可报的民办学校 =====
  {
    schoolId: 'mb13',
    name: '私立第一中学（其他县区）',
    fullName: '私立第一中学',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 710,
    tongZhao: 710,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费较高（以学校公布为准）',
    keyFeature: '统招线710分，面向全市其他县区招生',
    gaokaoRate: '本一率90%+',
    intro: '面向其他县区招生的民办高中，统招线710分，无一统线（非省示范）。',
    tips: '有新乐分配生名额（mb13暂无），统招线710分，属于较高门槛的民办学校。报考前请核实是否有新乐分配生名额及最新收费标准。',
  },
  {
    schoolId: 'mb14',
    name: '新世纪外国语学校（其他县区）',
    fullName: '新世纪外国语学校',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 700,
    tongZhao: 700,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费较高',
    keyFeature: '外语特色民办高中，面向全市招生',
    gaokaoRate: '本一率85%+',
    intro: '以外语为特色的民办高中，统招线700分，面向全市各县区招生。适合英语能力较强、有意向强化外语的学生。',
    tips: '统招线700分，外语特色突出。报考前请确认是否有新乐分配生名额及最新收费。',
  },
  {
    schoolId: 'mb15',
    name: '瀚林学校（其他县区）',
    fullName: '瀚林学校',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 695,
    tongZhao: 695,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等',
    keyFeature: '面向全市其他县区招生，统招线695分',
    intro: '面向其他县区招生的民办高中，统招线695分。',
    tips: '统招线695分，门槛适中。报考前请核实新乐分配生名额及收费。',
  },
  {
    schoolId: 'mb16',
    name: '西山学校（其他县区）',
    fullName: '西山学校',
    type: '民办',
    location: '鹿泉',
    address: '石家庄市鹿泉区',
    distanceFromXinle: '距新乐约70公里',
    yiTong: 718,
    tongZhao: 718,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费较高',
    keyFeature: '鹿泉知名民办高中，环境优美，统招线718分',
    gaokaoRate: '本一率90%+',
    intro: '位于鹿泉区的民办高中，校园环境优美，统招线718分，面向其他县区招生。',
    tips: '统招线718分，门槛较高。在鹿泉区就读，距新乐约70公里，需住校。',
  },
  {
    schoolId: 'mb17',
    name: '华西高级中学（其他县区）',
    fullName: '华西高级中学',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 666,
    tongZhao: 666,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等',
    keyFeature: '面向其他县区招生，统招线666分',
    intro: '面向其他县区招生的民办高中，统招线666分。',
    tips: '统招线666分，门槛适中。报考前请核实新乐分配生名额及收费。',
  },
  {
    schoolId: 'mb18',
    name: '耀华中学（其他县区）',
    fullName: '耀华中学',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 632,
    tongZhao: 632,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等',
    keyFeature: '面向其他县区，统招线632分',
    intro: '面向其他县区招生的民办高中，统招线632分。',
    tips: '统招线632分，门槛相对较低，适合中等偏上成绩学生。',
  },
  {
    schoolId: 'mb19',
    name: '华英外国语学校（其他县区）',
    fullName: '华英外国语学校',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 630,
    tongZhao: 630,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等',
    keyFeature: '外语特色民办，统招线630分',
    intro: '以外语为特色的民办高中，统招线630分，面向其他县区招生。',
    tips: '外语特色，统招线630分，适合英语能力较强学生。',
  },

  // ===== 第三批补充：其他县区县级公办学校 =====
  {
    schoolId: 'cx01',
    name: '藁城区第一中学',
    fullName: '藁城区第一中学',
    type: '省示范',
    location: '藁城',
    address: '石家庄市藁城区',
    distanceFromXinle: '距新乐约50公里',
    yiTong: 727,
    tongZhao: 709,
    enrollment: 700,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '藁城区最好高中，省级示范校',
    gaokaoRate: '本一率90%+',
    intro: '藁城区最顶尖公办省示范高中，一统线727分，统招线709分。位于藁城区，距新乐约50公里。',
    tips: '属于周边县区公办学校，新乐学生能否跨县报考需提前核实。藁城是新乐东邻，路程相对较近，但学校面向藁城户籍学生为主。',
  },
  {
    schoolId: 'cx02',
    name: '平山中学',
    fullName: '平山中学',
    type: '省示范',
    location: '平山',
    address: '石家庄市平山县',
    distanceFromXinle: '距新乐约80公里',
    yiTong: 720,
    tongZhao: 683,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '平山县最好高中，省级示范校',
    gaokaoRate: '本一率85%+',
    intro: '平山县省级示范性高中，一统线720分，统招线683分。',
    tips: '属于外县公办学校，新乐学生一般无法跨县报考公办高中。仅供参考。',
  },
  {
    schoolId: 'cx03',
    name: '无极中学',
    fullName: '无极中学',
    type: '省示范',
    location: '无极',
    address: '石家庄市无极县',
    distanceFromXinle: '距新乐约40公里',
    yiTong: 720,
    tongZhao: 666,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '无极县最好高中，省级示范校，距新乐较近',
    gaokaoRate: '本一率85%+',
    intro: '无极县省级示范性高中，一统线720分，统招线666分。无极县是新乐的邻县，距新乐约40公里。注：石家庄实验中学在无极县设有(无极)招生计划，统招线 750 分，属于优质选择。',
    tips: '无极是新乐邻县，距离相对较近。但新乐学生一般无法跨县报考公办高中，仅供参考。',
  },
  {
    schoolId: 'cx04',
    name: '赵县中学',
    fullName: '赵县中学',
    type: '省示范',
    location: '赵县',
    address: '石家庄市赵县',
    distanceFromXinle: '距新乐约80公里',
    yiTong: 722,
    tongZhao: 668,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '赵县最好高中，省级示范校',
    gaokaoRate: '本一率85%+',
    intro: '赵县省级示范性高中，一统线722分，统招线668分。',
    tips: '属于外县公办学校，新乐学生一般无法跨县报考，仅供参考。',
  },
  {
    schoolId: 'cx05',
    name: '行唐县第一中学',
    fullName: '行唐县第一中学',
    type: '省示范',
    location: '行唐',
    address: '石家庄市行唐县',
    distanceFromXinle: '距新乐约40公里',
    yiTong: 720,
    tongZhao: 657,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '行唐县最好高中，距新乐较近',
    gaokaoRate: '本一率80%+',
    intro: '行唐县省级示范高中，一统线720分，统招线657分。行唐是新乐的邻县，距新乐约40公里。',
    tips: '行唐是新乐邻县，距离较近。但新乐学生一般无法跨县报考公办高中，仅供参考。',
  },
  {
    schoolId: 'cx06',
    name: '晋州市第一中学',
    fullName: '晋州市第一中学',
    type: '省示范',
    location: '晋州',
    address: '石家庄市晋州市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: 711,
    tongZhao: 609,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '晋州市最好高中，省级示范校',
    gaokaoRate: '本一率80%+',
    intro: '晋州市省级示范高中，一统线711分，统招线609分。',
    tips: '外县公办学校，新乐学生通常无法跨县报考，仅供参考。',
  },
  {
    schoolId: 'cx07',
    name: '灵寿中学',
    fullName: '灵寿中学',
    type: '省示范',
    location: '灵寿',
    address: '石家庄市灵寿县',
    distanceFromXinle: '距新乐约50公里',
    yiTong: 713,
    tongZhao: 638,
    enrollment: 500,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '灵寿县最好高中，省级示范校',
    gaokaoRate: '本一率80%+',
    intro: '灵寿县省级示范高中，一统线713分，统招线638分。',
    tips: '外县公办学校，新乐学生通常无法跨县报考，仅供参考。',
  },
  {
    schoolId: 'cx08',
    name: '元氏县第一中学',
    fullName: '元氏县第一中学',
    type: '省示范',
    location: '元氏',
    address: '石家庄市元氏县',
    distanceFromXinle: '距新乐约80公里',
    yiTong: 705,
    tongZhao: 633,
    enrollment: 500,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '元氏县最好高中，省级示范校',
    gaokaoRate: '本一率80%+',
    intro: '元氏县省级示范高中，一统线705分，统招线633分。',
    tips: '外县公办学校，新乐学生通常无法跨县报考，仅供参考。',
  },
  {
    schoolId: 'cx09',
    name: '栾城中学',
    fullName: '栾城中学',
    type: '省示范',
    location: '栾城',
    address: '石家庄市栾城区',
    distanceFromXinle: '距新乐约70公里',
    yiTong: 724,
    tongZhao: 651,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '栾城区最好高中，省级示范校',
    gaokaoRate: '本一率85%+',
    intro: '栾城区省级示范高中，一统线724分，统招线651分。',
    tips: '外县区公办学校，新乐学生通常无法跨县报考，仅供参考。',
  },
  {
    schoolId: 'cx10',
    name: '正定县第一中学',
    fullName: '正定县第一中学',
    type: '省示范',
    location: '正定',
    address: '石家庄市正定县',
    distanceFromXinle: '距新乐约40公里',
    yiTong: 721,
    tongZhao: 689,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '正定县本地最好公办高中，勿与正定中学混淆',
    gaokaoRate: '本一率80%+',
    intro: '正定县本地公办省示范高中（注意：此为正定县第一中学，与驻县四所之一的"河北正定中学"不同），一统线721分，统招线689分。距新乐约40公里。',
    tips: '注意：此为正定县第一中学，不是顶尖的河北正定中学！外县学生通常无法报考县级公办学校，仅供了解参考。',
  },

  // ───── 缺失的县级公办省示范（新乐学生不可报，仅供参考）─────
  {
    schoolId: 'cx11',
    name: '鹿泉区第一中学',
    fullName: '鹿泉区第一中学',
    type: '省示范',
    location: '鹿泉',
    address: '石家庄市鹿泉区',
    distanceFromXinle: '距新乐约70公里',
    yiTong: 724,
    tongZhao: 678,
    enrollment: 600,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '鹿泉区最好高中，省级示范校，2025年统招678分',
    gaokaoRate: '本科上线率85%+',
    intro: '鹿泉区省级示范高中，2025年一统线724分，统招线678分。精英新华、卓越中学、西山学校、金石中学均位于鹿泉区，在此区就读选择较多。',
    tips: '⚠️ 新乐学生不可报考本地公办学校。鹿泉区有多所民办学校（精英新华、卓越西/东、金石、西山）接受新乐学生，可重点关注。',
  },
  {
    schoolId: 'cx12',
    name: '矿区中学',
    fullName: '矿区中学',
    type: '省示范',
    location: '井陉矿区',
    address: '石家庄市井陉矿区',
    distanceFromXinle: '距新乐约80公里',
    yiTong: 623,
    tongZhao: 540,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '井陉矿区公办省示范，录取门槛相对较低',
    intro: '井陉矿区公办省示范高中，2025年一统线623分，统招线540分，录取门槛在省示范中属较低水平。',
    tips: '⚠️ 新乐学生不可报考本地公办学校，仅供了解。',
  },
  {
    schoolId: 'cx13',
    name: '高邑一中',
    fullName: '高邑县第一中学',
    type: '省示范',
    location: '高邑',
    address: '石家庄市高邑县',
    distanceFromXinle: '距新乐约90公里',
    yiTong: 700,
    tongZhao: 603,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '高邑县省示范高中',
    intro: '高邑县省级示范高中，2025年一统线700分，统招线603分。',
    tips: '⚠️ 新乐学生不可报考本地公办学校，仅供了解参考。',
  },
  {
    schoolId: 'cx14',
    name: '深泽县中学',
    fullName: '深泽县中学',
    type: '省示范',
    location: '深泽',
    address: '石家庄市深泽县',
    distanceFromXinle: '距新乐约30公里，是距新乐最近的外县之一',
    yiTong: 662,
    tongZhao: 540,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '深泽县省示范，距新乐最近，录取线相对较低',
    intro: '深泽县省级示范高中，2025年一统线662分，统招线540分。深泽是新乐的邻县，地理位置最近。',
    tips: '⚠️ 新乐学生不可报考本地公办学校。深泽虽然距新乐近，但高考升学数据较弱，仅供了解。',
  },
  {
    schoolId: 'cx15',
    name: '赞皇中学',
    fullName: '赞皇中学',
    type: '省示范',
    location: '赞皇',
    address: '石家庄市赞皇县',
    distanceFromXinle: '距新乐约100公里',
    yiTong: 688,
    tongZhao: 571,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '赞皇县省示范高中',
    intro: '赞皇县省级示范高中，2025年一统线688分，统招线571分。',
    tips: '⚠️ 新乐学生不可报考本地公办学校，仅供了解参考。',
  },
  {
    schoolId: 'cx16',
    name: '井陉县第一中学',
    fullName: '井陉县第一中学',
    type: '省示范',
    location: '井陉',
    address: '石家庄市井陉县',
    distanceFromXinle: '距新乐约90公里',
    yiTong: 705,
    tongZhao: 606,
    enrollment: 500,
    boardingAvail: true,
    boardingFee: '约300元/学期',
    tuitionFee: '公办，学费全免',
    keyFeature: '井陉县省示范高中',
    intro: '井陉县省级示范高中，2025年一统线705分，统招线606分。',
    tips: '⚠️ 新乐学生不可报考本地公办学校，仅供了解参考。',
  },

  // ───── 缺失的民办学校（其他县区计划，新乐学生可报）─────
  {
    schoolId: 'mb20',
    name: '精英未来高级中学（其他县区）',
    fullName: '石家庄精英未来高级中学有限公司',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: null,
    tongZhao: 662,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等（以学校公布为准）',
    keyFeature: '2023年新建，精英集团旗下，其他县区统招662分',
    intro: '精英教育集团旗下新建民办高中，建于2023年，配备理化生实验室、信息技术教室等标准设施。2025年其他县区统招线662分，隶属精英系但学费相对较低。',
    tips: '✅ 新乐学生可以报考（其他县区计划），统招线662分，门槛相对较低。学校较新，高考成绩数据有限，报考前建议向学校核实师资情况。',
  },
  {
    schoolId: 'mb21',
    name: '云臻实验高级中学（其他县区）',
    fullName: '云臻实验高级中学有限公司',
    type: '民办',
    location: '市区',
    address: '石家庄市',
    distanceFromXinle: '距新乐约60公里',
    yiTong: null,
    tongZhao: 591,
    enrollment: 400,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费中等（以学校公布为准）',
    keyFeature: '统招线591分，门槛较低，有免费班（头部学生奖学金）',
    intro: '石家庄民办高中，2025年其他县区统招线591分，在民办学校中属于录取门槛较低的学校。对于顶尖学生可能有免费班名额（须咨询学校）。',
    tips: '✅ 新乐学生可以报考（其他县区计划），统招线591分，是门槛较低的民办选择。建议优先了解师资和学费情况再报考。',
  },
  {
    schoolId: 'mb22',
    name: '北华中学（其他县区）',
    fullName: '北华中学',
    type: '民办',
    location: '正定',
    address: '石家庄市正定县',
    distanceFromXinle: '距新乐约40公里',
    yiTong: null,
    tongZhao: 540,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费较低（以学校公布为准）',
    keyFeature: '正定民办高中，统招线540分，录取门槛最低之一，距新乐较近',
    intro: '位于正定县的民办高中，2025年其他县区统招线540分，是石家庄民办高中中门槛最低的学校之一，距新乐约40公里。',
    tips: '✅ 新乐学生可以报考，统招线540分，门槛极低。适合分数相对较低但希望读高中的学生。距新乐较近是一大优势。',
  },
  {
    schoolId: 'mb23',
    name: '麒麟私立中学（其他县区）',
    fullName: '麒麟私立中学',
    type: '民办',
    location: '正定',
    address: '石家庄市正定县',
    distanceFromXinle: '距新乐约40公里',
    yiTong: null,
    tongZhao: 422,
    enrollment: 300,
    boardingAvail: true,
    boardingFee: '住宿费另计',
    tuitionFee: '民办，学费较低（以学校公布为准）',
    keyFeature: '正定民办高中，其他县区统招422分，面向中低分段学生',
    intro: '位于正定县的民办高中，2025年其他县区统招线422分，是石家庄录取门槛最低的民办高中之一。',
    tips: '✅ 新乐学生可以报考，统招线422分（其他县区），适合分数较低但仍希望就读普通高中的学生。报考前请务必了解学费标准和升学率。',
  },
]

async function main() {
  console.log('开始初始化学校数据...')
  for (const school of schools) {
    await prisma.highSchoolInfo.upsert({
      where: { schoolId: school.schoolId },
      update: school,
      create: school,
    })
    console.log(`✓ ${school.name}`)
  }
  console.log(`完成！共写入 ${schools.length} 所学校信息`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
